name: Scala CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Run tests
        env:
          KUBE_CONFIG_TEMPLATE: """apiVersion: v1
                                               clusters:
                                               - cluster:
                                                   certificate-authority-data: DATA+OMITTED
                                                   server: https://kubernetes.docker.internal:6443
                                                 name: docker-desktop
                                               contexts:
                                               - context:
                                                   cluster: docker-desktop
                                                   user: docker-desktop
                                                 name: docker-desktop
                                               - context:
                                                   cluster: docker-desktop
                                                   user: docker-desktop
                                                 name: docker-for-desktop
                                               current-context: docker-desktop
                                               kind: Config
                                               preferences: {}
                                               users:
                                               - name: docker-desktop
                                                 user:
                                                   client-certificate-data: REDACTED
                                                   client-key-data: REDACTED"""
        run: |
              export KUBE_CONFIG_TEMP= $KUBE_CONFIG_TEMPLATE
      - name: echo test
        run: |
            echo Hello there!
