name: Scala CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Run tests
        run: sbt "project modbusTranslator" test
    - name: Install kubectl
        run: |
              curl -LO https://storage.googleapis.com/kubernetes-release/release/`curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt`/bin/linux/amd64/kubectl
              chmod +x ./kubectl
       - name: Configure kubectl
            env:
              VAULT_TOKEN: ${{ secrets.VAULT_TOKEN }}
              KUBE_CONFIG_TEMPLATE: "apiVersion: v1
                                     clusters:
                                     - cluster:
                                         certificate-authority-data: DATA+OMITTED
                                         server: https://kubernetes.docker.internal:6443
                                       name: docker-desktop
                                     contexts:
                                     - context:
                                         cluster: docker-desktop
                                         user: docker-desktop
                                       name: docker-desktop
                                     - context:
                                         cluster: docker-desktop
                                         user: docker-desktop
                                       name: docker-for-desktop
                                     current-context: docker-desktop
                                     kind: Config
                                     preferences: {}
                                     users:
                                     - name: docker-desktop
                                       user:
                                         client-certificate-data: REDACTED
                                         client-key-data: REDACTED"
            run: |
              KUBE_CONFIG= $KUBE_CONFIG_TEMPLATE
              export KUBECONFIG=$KUBE_CONFIG
       - name: Run tests
          run: echo $KUBECONFIG
