name: Scala CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Run tests
        env:
          KUBE_CONFIG_TEMPLATE: file_path
        run: |
              export KUBE_CONFIG_TEMP= $KUBE_CONFIG_TEMPLATE
      - name: echo test
        run: |
            echo "$file_path"
